import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Injectable } from '@nestjs/common';
import type { PhotoType } from '@leaselens/shared';

const EXT: Record<PhotoType, string> = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };

/** Keys are always generated by the server, so anything else is rejected (blocks "../" tricks). */
const KEY_PATTERN = /^work-orders\/[0-9a-f-]{36}\.(jpg|png|webp)$/;

export function newPhotoKey(contentType: PhotoType): string {
  return `work-orders/${randomUUID()}.${EXT[contentType]}`;
}

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error(`Invalid storage key: ${key}`);
}

/** Where files live. Local disk in development; Cloud Storage replaces this in production. */
export abstract class StorageService {
  abstract save(key: string, data: Buffer): Promise<void>;
  abstract read(key: string): Promise<Buffer>;
  abstract delete(key: string): Promise<void>;
}

/** Repo-root `uploads/` (gitignored) unless UPLOADS_DIR is set. */
export function defaultUploadsDir(): string {
  // src/storage and dist/storage are both four levels below the repo root.
  return process.env.UPLOADS_DIR ?? path.resolve(__dirname, '../../../../uploads');
}

@Injectable()
export class LocalStorageService extends StorageService {
  constructor(private readonly root: string = defaultUploadsDir()) {
    super();
  }

  private fullPath(key: string): string {
    assertValidKey(key);
    return path.join(this.root, ...key.split('/'));
  }

  async save(key: string, data: Buffer): Promise<void> {
    const file = this.fullPath(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data, { flag: 'wx' }); // never overwrite
  }

  async read(key: string): Promise<Buffer> {
    return readFile(this.fullPath(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.fullPath(key), { force: true });
  }
}
